apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql-deployment
  namespace: mysql
  labels:
    app: mysql
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      namespace: mysql
      labels:
        app: mysql
    spec: 
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: MYSQL_DATABASE
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: MYSQL_PASSWORD
        volumeMounts:
        - name: mysql-pv-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pv-volume
        persistentVolumeClaim:
          claimName: mysql-pv-claim 
