apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: mysql
  name: mysql-pv-volume
  labels:
    app: mysql
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
