apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  namespace: nginx-group
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-pod
        image: nginx:latest
        ports:
        - containerPort: 80
